version: '3.6'
services:

  botsdb:
    image: mariadb
    networks: 
      - net_bots_backend
    container_name: botwebserver_database
    user: root
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=bots"
      - "MYSQL_USER=botuser"
      - "MYSQL_PASSWORD=pewpewpew"
    volumes:
      - botwebserver-mariadb:/var/lib/mysql

  botsadmin:
    image: adminer
    restart: always
    networks: 
      - net_bots_backend
      #- net_account_backend
    ports:
      - 8080:8080

  botsserver:
    networks: 
      - net_bots_backend
    build:
      network: host
      context: ./
      dockerfile: ./BotWebServer/Dockerfile
    ports:
      - "5000:80"
    depends_on: 
      - botsdb
    
networks:
  net_bots_backend:
    name: bots_backend
  net_account_backend:
    name: account_backend

volumes:
  # docker volume create botwebserver-mariadb
  botwebserver-mariadb:
    external: true  
