version: '3.6'
services:

  database:
    image: mariadb
    networks: 
      - prod
    container_name: botwebserver_database
    user: root
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=bots"
      - "MYSQL_USER=botuser"
      - "MYSQL_PASSWORD=pewpewpew"
    volumes:
      - botwebserver-mariadb:/var/lib/mysql
    ports:
      - "5306:3306"

  adminer:
    image: adminer
    restart: always
    networks: 
      - prod
    ports:
      - 8080:8080

  dfcommonlib:
    build:
      network: host
      context: ./
      dockerfile: ./DFCommonLib/Dockerfile
    volumes:
      - ./NuGet:/nuget

  botserver:
    networks: 
      - prod
    build:
      network: host
      context: ./
      dockerfile: ./BotWebServer/Dockerfile
    ports:
      - "5000:80"
    depends_on: 
      - database
      - dfcommonlib
    links:
      - database:db
  
networks:
  prod:
    name: custom_frontend

volumes:
  # docker volume create botwebserver-mariadb
  botwebserver-mariadb:
    external: true  