version: '3.6'
services:

  botsdb:
    image: mariadb
    networks: 
      - net_bots_backend
    container_name: botwebserver_database
    user: root
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=bots"
      - "MYSQL_USER=botuser"
      - "MYSQL_PASSWORD=pewpewpew"
    volumes:
      - botwebserver-mariadb:/var/lib/mysql
    ports:
      - 5306:3306

  botsadmin:
    image: adminer
    restart: always
    networks: 
      - net_bots_backend
      #- net_account_backend
    environment: 
      ADMINER_DEFAULT_SERVER: botsdb
    ports:
      - 8180:8080

  botsserver:
    networks: 
      - net_bots_backend
    build:
      network: host
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "5000:80"
#    environment:
#      - ASPNETCORE_URLS=https://+:443;http://+:80
#      - ASPNETCORE_Kestrel__Certificates__Default__Password=smurfepoliz
#      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certificate.pfx
    depends_on: 
      - botsdb
    
networks:
  net_bots_backend:
    name: bots_backend
volumes:
  # docker volume create botwebserver-mariadb
  botwebserver-mariadb:
    external: true  
