#
# Build Deploy file for Docker container
# Change the variables in this section to match your project
#

name: Bot Server - Deploy

defaults:
  run:
    working-directory: .

on:
  release:
    types: [published]

  pull_request:
    types: [closed]
    branches: ["master", "main"]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  staging:
    if: github.event.pull_request.merged == true || github.event.inputs.environment == 'staging' || github.event.inputs.environment == 'production'
    name: Deploy to Staging
    uses: DarkFactorAS/Infrastructure/.github/workflows/infrastructure-server-deploy.yml@v1.1
    with:
      environment: staging
      project_path: "Server/BotWebServer"
      project_name: "BotWebServer"
      config_settings: "accountserver"
    secrets: inherit

  production:
    if: github.event.pull_request.merged == true || github.event.inputs.environment == 'production' || github.event_name == 'release'
    name: Deploy to Production
    uses: DarkFactorAS/Infrastructure/.github/workflows/infrastructure-server-deploy.yml@v1.1
    with:
      environment: production
      project_path: "Server/BotWebServer"
      project_name: "BotWebServer"
      config_settings: "accountserver"
    secrets: inherit
    needs: staging
